{
 "title": "Prisma",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(prisma_datasource_queries_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prisma_pool_connections_busy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prisma_pool_connections_idle)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(prisma_pool_connections_idle{service=\"$service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(prisma_pool_connections_busy{service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(prisma_client_queries_active{service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(prisma_client_queries_wait{service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(prisma_client_queries_duration_histogram_ms_bucket{service=\"$service\", le!=\"0\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Wait Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(prisma_client_queries_wait_histogram_ms_bucket{service=\"$service\", le!=\"0\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}